// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi-Bsg5t5s7djrmeF62cEImSWuWMT8OtE',
    appId: '1:530834537585:web:cb1c786948409e332f6fd0',
    messagingSenderId: '530834537585',
    projectId: 'chatapp-5c559',
    authDomain: 'chatapp-5c559.firebaseapp.com',
    storageBucket: 'chatapp-5c559.appspot.com',
    measurementId: 'G-M0E3Q69DL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXlQHivqBLc1TzyHjD5TvnJBkx7imQ9yQ',
    appId: '1:530834537585:android:1861df17e67b08e32f6fd0',
    messagingSenderId: '530834537585',
    projectId: 'chatapp-5c559',
    storageBucket: 'chatapp-5c559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwpdpEUdt33lFedOgINnPQELYIDsv8zrA',
    appId: '1:530834537585:ios:de0ae250dd5527e82f6fd0',
    messagingSenderId: '530834537585',
    projectId: 'chatapp-5c559',
    storageBucket: 'chatapp-5c559.appspot.com',
    androidClientId: '530834537585-j7bj2os44kcuvp7ifko5qt4r5n8indfl.apps.googleusercontent.com',
    iosClientId: '530834537585-n799qickca4tf3qtra6gs59oiae43d9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwpdpEUdt33lFedOgINnPQELYIDsv8zrA',
    appId: '1:530834537585:ios:de0ae250dd5527e82f6fd0',
    messagingSenderId: '530834537585',
    projectId: 'chatapp-5c559',
    storageBucket: 'chatapp-5c559.appspot.com',
    androidClientId: '530834537585-j7bj2os44kcuvp7ifko5qt4r5n8indfl.apps.googleusercontent.com',
    iosClientId: '530834537585-n799qickca4tf3qtra6gs59oiae43d9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi-Bsg5t5s7djrmeF62cEImSWuWMT8OtE',
    appId: '1:530834537585:web:4896efc1cd8d58992f6fd0',
    messagingSenderId: '530834537585',
    projectId: 'chatapp-5c559',
    authDomain: 'chatapp-5c559.firebaseapp.com',
    storageBucket: 'chatapp-5c559.appspot.com',
    measurementId: 'G-QPDGX1K9PQ',
  );
}
